services:

  nginx:
    build:
      context: ./api_gateway/nginx_docker
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - custom
    volumes:
      - ./api_gateway/lua-resty-jwt:/etc/nginx/lua-resty-jwt
      - ./api_gateway/lua-resty-hmac:/etc/nginx/lua-resty-hmac
    depends_on:
      - auth
      - store

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    networks:
      - custom

    ports:
      - "8000:8000"
    depends_on:
      - auth_db

  auth_db:
    image: postgres:13
    networks:
      - custom
    environment:
      POSTGRES_DB: eatit_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    container_name: store
    volumes:
      - app-logs:/logs
    networks:
      - custom
    ports:
      - "8001:8001"
    depends_on:
      - store_db

  store_db:
    image: postgres:13
    networks:
      - custom
    environment:
      POSTGRES_DB: eatit_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  basket:
    build:
      context: ./basket
      dockerfile: Dockerfile
    container_name: basket
    networks:
      - custom
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - custom

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - custom

  beats:
    image: elastic/filebeat:7.16.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./elk-configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - app-logs:/var/app/log
    networks:
      - custom
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./elk-configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    networks:
      - custom
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:7.16.2
    volumes:
      - ./elk-configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk-configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./elk-configs/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - custom
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    depends_on:
      - elasticsearch
    volumes:
      - ./elk-configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - custom
    ports:
      - "5601:5601"


volumes:
  app-logs:

networks:
  custom:
    driver: bridge